name: Push to Other Remote

on:
  push:
    branches:
      - master

jobs:
  push-to-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Add remote
        run: |
          git remote add other-repo ${{ env.OTHER_REPO }}

      - name: Push to other remote
        run: |
          git push other-repo master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
